version: "3"

volumes:
    postfix-logs:
    postfix-socket:

services:
    smtp_relay_server:
        build:
            context: ./smtp-relay
        environment:
            ENV: "${ENV}"
            PUBLIC_DNS_ZONE_NAME_STAFF_SERVICE: "${PUBLIC_DNS_ZONE_NAME_STAFF_SERVICE}"
            RELAY_DOMAIN: "${RELAY_DOMAIN}"
            O365_SMART_HOST: "${O365_SMART_HOST}"
        volumes:
            - postfix-logs:/var/log/mail
            - postfix-socket:/var/spool/postfix
        links:
            - smtp_relay_monitoring
    smtp_relay_test:
        build:
            context: ./smtp-relay-test
        environment:
            TEST_SENDER_EMAIL_ADDRESS: "${TEST_SENDER_EMAIL_ADDRESS}"
            O365_TEST_RECIPIENT_EMAIL_ADDRESS: "${O365_TEST_RECIPIENT_EMAIL_ADDRESS}"
            GOOGLE_TEST_RECIPIENT_EMAIL_ADDRESS: "${GOOGLE_TEST_RECIPIENT_EMAIL_ADDRESS}"
            OTHER_TEST_RECIPIENT_EMAIL_ADDRESS: "${OTHER_TEST_RECIPIENT_EMAIL_ADDRESS}"
    smtp_relay_monitoring:
        build:
            context: ./smtp-relay-monitoring
        volumes:
            - postfix-logs:/var/log/mail
            - postfix-socket:/var/spool/postfix
