version: "3"

volumes:
    postfix-logs:
    postfix-socket:


services:
    smtp_relay_server:
        platform: linux/amd64
        build:
            context: ./smtp-relay
        environment:
            ENV: "${ENV}"
            PUBLIC_DNS_ZONE_NAME_STAFF_SERVICE: "${PUBLIC_DNS_ZONE_NAME_STAFF_SERVICE}"
            RELAY_DOMAIN: "devl.justice.gov.uk"
            O365_SMART_HOST: "devl-justice-gov-uk.mail.protection.outlook.com"
            IP_ALLOWED_LIST: "127.0.0.0/8,172.16.0.0/24,13.40.249.195/32,10.180.104.0/22"
        volumes:
            - postfix-logs:/var/log/mail
            - postfix-socket:/var/spool/postfix
        links:
            - smtp_relay_monitoring
        networks:
            known:
                ipv4_address: 172.16.0.10
            unknown:
                ipv4_address: 172.16.1.10
    smtp_relay_test:
        platform: linux/amd64
        build:
            context: ./smtp-relay-test
        environment:
            TEST_SENDER_EMAIL_ADDRESS: "testuser@devl.justice.gov.uk"
            O365_TEST_RECIPIENT_EMAIL_ADDRESS: "${O365_TEST_RECIPIENT_EMAIL_ADDRESS}"
            GOOGLE_TEST_RECIPIENT_EMAIL_ADDRESS: "lanwifi-devops@digital.justice.gov.uk"
            OTHER_TEST_RECIPIENT_EMAIL_ADDRESS: "sandhyab1506@yahoo.com"
        networks:
            - known
            - unknown
    smtp_relay_monitoring:
        platform: linux/amd64
        build:
            context: ./smtp-relay-monitoring
        volumes:
            - postfix-logs:/var/log/mail
            - postfix-socket:/var/spool/postfix
        networks:
            - known

networks:
    known:
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/24
    unknown:
        ipam:
            driver: default
            config:
                - subnet: 172.16.1.0/24
