version: "3"
services:
    smtp_relay_server:
        build:
            context: ./smtp-relay
            args: 
                SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        environment:
            RELAY_DOMAIN: "${RELAY_DOMAIN}"
            RELAY_SMART_HOST: "${RELAY_SMART_HOST}"
    smtp_relay_test:
        build:
            context: ./smtp-relay-test
            args: 
                SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        environment:
            TEST_EMAIL_ADDRESS: "${TEST_EMAIL_ADDRESS}"
            MAILBOX_FOR_TEST_EMAIL: "${MAILBOX_FOR_TEST_EMAIL}"
